version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: video-share
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=video-share
    ports:
      - 5432:5432
